use nfl_adlister;

TRUNCATE ads;

INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (1, 'CeeDee Lamb', 9, 8, 88, 4500);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (1, 'Hjalte Frohodt', 1, 1, 72, 2500);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (2, 'Will Hernadez', 1, 2, 76, 2500);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (2, 'Kaleb Mcgary', 2, 3, 76, 2500);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (3, 'Taylor Heinicke', 2, 4, 4, 6000);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (3, 'J.K. Dobbins', 3, 5, 27, 5000);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (2, 'Odell Beckham Jr', 3, 6, 3, 4500);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (2, 'Dawson Knox', 4, 7, 86, 4000);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (1, 'Eli Ankou', 4, 8, 51, 3000);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (1, 'Henry Anderson', 5, 9, 94, 3000);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (1, 'Brian Burns', 5, 10, 0, 3000);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (1, 'DeMarquis Gates', 6, 11, 43, 3250);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (2, 'Josh Blackwell', 6, 12, 39, 2550);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (2, 'Tycen Anderson', 7, 13, 26, 1759);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (3, 'Evan McPherson', 7, 14, 2, 2004);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (3, 'Corey Bojorquez', 8, 15, 13, 2800);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (3, 'Corey Bojorquz', 8, 16, 13, 4000);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (3, 'KaVontae Turpin', 9, 17, 9, 2768);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (2, 'Deuce Vaughn', 9, 18, 42, 3457);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (2, 'Marvin Mims Jr ', 10, 19, 19, 3673);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (1, 'Jaleel Mclaughlin', 10, 18, 38, 2345);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (1, 'Jake Mcquaide', 11, 17, 43, 3221);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (1, 'Jack Fox', 11, 16, 3, 2222);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (1, 'Daniel Whelan', 12, 15, 19, 2357);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (2, 'Ander Carlson', 12, 14, 17, 3456);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (2, 'Grayland Arnold', 13, 13, 25, 2333);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (3, 'Kris Boyd ', 13, 12, 17, 2346);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (3, 'Liam Anderson', 14, 11, 47, 4322);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (3, 'Zaire Franklin', 14, 10, 44, 2235);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (3, 'Angelo Blackson', 15, 9, 90, 5643);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (2, 'Folorunso Fatukasi ', 15, 8, 94, 2345);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (2, 'Travis Kelce', 16, 7, 87, 4444);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (1, 'Skyy Moore', 16, 6, 24, 3333);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (1, 'Josh Jacob ', 17, 5, 8, 2222);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (1, 'Jimmy Garoppolo ', 17, 4, 10, 3333);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (1, 'Foster Sarell', 18, 3, 73, 4444);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (2, 'Zion Johnson', 18, 2, 77, 2335);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (2, 'Mike McAllister', 19, 1, 68, 4444);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (3, 'Logan Bruss', 19, 2, 60, 4324);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (3, 'Kendall Lamm ', 20, 3, 70, 4321);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (3, 'Tua Tagovailoa', 20, 4, 1, 3333);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (3, 'Alexander Mattison', 21, 5, 2, 2222);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (2, 'Justin Jefferson', 21, 6, 18, 6593);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (2, 'Hunter Henry', 22, 7, 85, 3378);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (1, 'Keion White', 22, 8, 99, 2479);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (1, 'Cameron Jordan', 23, 9, 94, 4444);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (1, 'Andrew Dowell', 23, 10, 50, 4579);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (1, 'Tomon Fox', 24, 11, 49, 3579);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (2, 'Kaleb Hayes', 24, 12, 38, 2398);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (2, 'Adrian Amos', 25, 13, 0, 3456);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (3, 'Greg Zuerlein', 25, 14, 9, 5555);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (3, 'Branden Mann', 26, 15, 10, 3258);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (3, 'Brandon Mann', 26, 16, 1, 4225);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (3, 'Chrisian Kuntz', 27, 17, 46, 2358);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (2, 'Anthony Macfarland Jr', 27, 18, 26, 5432);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (2, 'Ray McClouid III', 28, 19, 3, 2357);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (1, 'Ronnie Bell', 28, 18, 10, 3277);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (1, 'Chris Stoll', 29, 17, 41, 3234);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (1, 'Michael Dickson', 29, 16, 4, 3457);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (1, 'Jake Camarda', 30, 15, 5, 1245);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (2, 'Chase McLaughlin', 30, 14, 4, 4444);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (2, 'Amani Hooker ', 31, 13, 37, 2222);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (3, 'Caleb Farley', 31, 12, 3, 1111);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (3, 'Cody Barton ', 32, 11, 57, 3555);
INSERT INTO nfl_adlister.ads (user, player, player_team, player_position, number, price) VALUES (2, 'Jabril Cox', 32, 10, 41, 3245);



