use nfl_adlister;

INSERT INTO nfl_adlister.position (position_name) VALUES ('Center');
INSERT INTO nfl_adlister.position (position_name) VALUES ('Offensive Guard');
INSERT INTO nfl_adlister.position (position_name) VALUES ('Offensive Tackle ');
INSERT INTO nfl_adlister.position (position_name) VALUES ('Quaterback');
INSERT INTO nfl_adlister.position (position_name) VALUES ('Running Back');
INSERT INTO nfl_adlister.position (position_name) VALUES ('Wide Receiver');
INSERT INTO nfl_adlister.position (position_name) VALUES ('Tight End');
INSERT INTO nfl_adlister.position (position_name) VALUES ('Defensive Tackle ');
INSERT INTO nfl_adlister.position (position_name) VALUES ('Defensive End ');
INSERT INTO nfl_adlister.position (position_name) VALUES ('Middle Linebacker');
INSERT INTO nfl_adlister.position (position_name) VALUES ('Outside Linebacker');
INSERT INTO nfl_adlister.position (position_name) VALUES ('Cornerback');
INSERT INTO nfl_adlister.position (position_name) VALUES ('Safety ');
INSERT INTO nfl_adlister.position (position_name) VALUES ('Kicker');
INSERT INTO nfl_adlister.position (position_name) VALUES ('Punter');
INSERT INTO nfl_adlister.position (position_name) VALUES ('Holder');
INSERT INTO nfl_adlister.position (position_name) VALUES ('Long Snapper');
INSERT INTO nfl_adlister.position (position_name) VALUES ('Kick Returner');
INSERT INTO nfl_adlister.position (position_name) VALUES ('Punt Returner');
